import { Logger } from '@nestjs/common';
import { StudyGuideMoodleService } from '../../../src/context/study-guide-moodle.service';

type MoodleDouble = {
  callMoodleApi: jest.Mock;
  toPublicMoodleUrl: jest.Mock;
};

type PlacementDouble = {
  ensureStudentPlacement: jest.Mock;
};

const PAGE_RESPONSE = {
  pageid: 77,
  cmid: 601,
  name: 'Study Guide: Week 1',
  viewurl: 'http://webserver/mod/page/view.php?id=601',
};

describe('StudyGuideMoodleService', () => {
  let moodle: MoodleDouble;
  let placement: PlacementDouble;
  let service: StudyGuideMoodleService;

  beforeEach(() => {
    jest.spyOn(Logger.prototype, 'warn').mockImplementation();
    moodle = {
      callMoodleApi: jest.fn().mockResolvedValue(PAGE_RESPONSE),
      toPublicMoodleUrl: jest.fn((raw: string) => `public:${raw}`),
    };
    placement = {
      ensureStudentPlacement: jest.fn().mockResolvedValue({
        sectionId: 7,
        sectionNum: 3,
        groupId: 21,
        groupName: 'AI Content',
        availabilityJson: '{}',
      }),
    };
    service = new StudyGuideMoodleService(moodle as never, placement as never);
  });

  afterEach(() => {
    jest.restoreAllMocks();
  });

  describe('createStudyGuide', () => {
    it('ensures placement and POSTs local_syllentras_ai_create_study_guide', async () => {
      await service.createStudyGuide({
        courseId: 12,
        moodleUserId: 42,
        name: 'Study Guide: Week 1',
        intro: 'Generated by Syllentras',
        contentHtml: '<p>Mitosis</p>',
      });

      expect(placement.ensureStudentPlacement).toHaveBeenCalledWith(12, 42);
      expect(moodle.callMoodleApi).toHaveBeenCalledWith(
        'local_syllentras_ai_create_study_guide',
        {
          courseid: 12,
          userid: 42,
          name: 'Study Guide: Week 1',
          intro: 'Generated by Syllentras',
          content: '<p>Mitosis</p>',
        },
        'POST',
      );
    });

    it('defaults intro to an empty string when omitted', async () => {
      await service.createStudyGuide({
        courseId: 12,
        moodleUserId: 42,
        name: 'Study Guide',
        contentHtml: '<p>Body</p>',
      });

      expect(moodle.callMoodleApi.mock.calls[0][1]).toMatchObject({ intro: '' });
    });

    it('maps the response into CreatedStudyGuide with a public view URL', async () => {
      await expect(
        service.createStudyGuide({
          courseId: 12,
          moodleUserId: 42,
          name: 'Study Guide: Week 1',
          contentHtml: '<p>Mitosis</p>',
        }),
      ).resolves.toEqual({
        pageId: 77,
        cmId: 601,
        name: 'Study Guide: Week 1',
        viewUrl: 'public:http://webserver/mod/page/view.php?id=601',
      });
      expect(moodle.toPublicMoodleUrl).toHaveBeenCalledWith(
        'http://webserver/mod/page/view.php?id=601',
      );
    });

    it('rejects courseId <= 1 before touching placement or Moodle', async () => {
      await expect(
        service.createStudyGuide({
          courseId: 1,
          moodleUserId: 42,
          name: 'Guide',
          contentHtml: '<p>Body</p>',
        }),
      ).rejects.toThrow('courseId must be a real course (greater than 1)');

      expect(placement.ensureStudentPlacement).not.toHaveBeenCalled();
      expect(moodle.callMoodleApi).not.toHaveBeenCalled();
    });

    it('rejects moodleUserId < 1', async () => {
      await expect(
        service.createStudyGuide({
          courseId: 12,
          moodleUserId: 0,
          name: 'Guide',
          contentHtml: '<p>Body</p>',
        }),
      ).rejects.toThrow('moodleUserId must be a positive integer');
      expect(moodle.callMoodleApi).not.toHaveBeenCalled();
    });

    it('rejects whitespace-only contentHtml', async () => {
      await expect(
        service.createStudyGuide({
          courseId: 12,
          moodleUserId: 42,
          name: 'Guide',
          contentHtml: '   \n\t ',
        }),
      ).rejects.toThrow('contentHtml is required');
      expect(moodle.callMoodleApi).not.toHaveBeenCalled();
    });

    it('does not create the page when placement fails', async () => {
      placement.ensureStudentPlacement.mockRejectedValue(
        new Error('Moodle API exception: cannotcreategroup'),
      );

      await expect(
        service.createStudyGuide({
          courseId: 12,
          moodleUserId: 42,
          name: 'Guide',
          contentHtml: '<p>Body</p>',
        }),
      ).rejects.toThrow('Moodle API exception: cannotcreategroup');

      expect(moodle.callMoodleApi).not.toHaveBeenCalled();
    });

    it('propagates failures from the page creation call', async () => {
      moodle.callMoodleApi.mockRejectedValue(new Error('Moodle API error: 500'));

      await expect(
        service.createStudyGuide({
          courseId: 12,
          moodleUserId: 42,
          name: 'Guide',
          contentHtml: '<p>Body</p>',
        }),
      ).rejects.toThrow('Moodle API error: 500');
      expect(moodle.toPublicMoodleUrl).not.toHaveBeenCalled();
    });
  });

  describe('createPrivatePage', () => {
    it('delegates to the same Moodle web service as createStudyGuide', async () => {
      const result = await service.createPrivatePage({
        courseId: 12,
        moodleUserId: 42,
        name: 'Flashcards',
        intro: 'intro text',
        contentHtml: '<p>Cards</p>',
      });

      expect(moodle.callMoodleApi).toHaveBeenCalledWith(
        'local_syllentras_ai_create_study_guide',
        {
          courseid: 12,
          userid: 42,
          name: 'Flashcards',
          intro: 'intro text',
          content: '<p>Cards</p>',
        },
        'POST',
      );
      expect(result).toEqual({
        pageId: 77,
        cmId: 601,
        name: 'Study Guide: Week 1',
        viewUrl: 'public:http://webserver/mod/page/view.php?id=601',
      });
    });

    it('applies the same validation rules as createStudyGuide', async () => {
      await expect(
        service.createPrivatePage({
          courseId: 12,
          moodleUserId: 42,
          name: 'Flashcards',
          contentHtml: '',
        }),
      ).rejects.toThrow('contentHtml is required');
      expect(placement.ensureStudentPlacement).not.toHaveBeenCalled();
    });
  });

  describe('updatePrivatePage', () => {
    it('POSTs local_syllentras_ai_update_private_page without ensuring placement', async () => {
      await service.updatePrivatePage({
        courseId: 12,
        moodleUserId: 42,
        cmId: 601,
        contentHtml: '<p>Updated</p>',
      });

      expect(moodle.callMoodleApi).toHaveBeenCalledWith(
        'local_syllentras_ai_update_private_page',
        { cmid: 601, userid: 42, content: '<p>Updated</p>' },
        'POST',
      );
      expect(placement.ensureStudentPlacement).not.toHaveBeenCalled();
    });

    it('includes a trimmed name only when a non-blank name is supplied', async () => {
      await service.updatePrivatePage({
        courseId: 12,
        moodleUserId: 42,
        cmId: 601,
        contentHtml: '<p>Updated</p>',
        name: '  Renamed Guide  ',
      });

      expect(moodle.callMoodleApi.mock.calls[0][1]).toEqual({
        cmid: 601,
        userid: 42,
        content: '<p>Updated</p>',
        name: 'Renamed Guide',
      });
    });

    it('omits name when it is whitespace only', async () => {
      await service.updatePrivatePage({
        courseId: 12,
        moodleUserId: 42,
        cmId: 601,
        contentHtml: '<p>Updated</p>',
        name: '   ',
      });

      expect(moodle.callMoodleApi.mock.calls[0][1]).toEqual({
        cmid: 601,
        userid: 42,
        content: '<p>Updated</p>',
      });
    });

    it('maps the response into CreatedStudyGuide with a public view URL', async () => {
      await expect(
        service.updatePrivatePage({
          courseId: 12,
          moodleUserId: 42,
          cmId: 601,
          contentHtml: '<p>Updated</p>',
        }),
      ).resolves.toEqual({
        pageId: 77,
        cmId: 601,
        name: 'Study Guide: Week 1',
        viewUrl: 'public:http://webserver/mod/page/view.php?id=601',
      });
    });

    it('rejects invalid courseId, moodleUserId, cmId, and blank content', async () => {
      const base = {
        courseId: 12,
        moodleUserId: 42,
        cmId: 601,
        contentHtml: '<p>Updated</p>',
      };

      await expect(
        service.updatePrivatePage({ ...base, courseId: 1 }),
      ).rejects.toThrow('courseId must be a real course (greater than 1)');
      await expect(
        service.updatePrivatePage({ ...base, moodleUserId: 0 }),
      ).rejects.toThrow('moodleUserId must be a positive integer');
      await expect(
        service.updatePrivatePage({ ...base, cmId: 0 }),
      ).rejects.toThrow('cmId must be a positive integer');
      await expect(
        service.updatePrivatePage({ ...base, contentHtml: '  ' }),
      ).rejects.toThrow('contentHtml is required');

      expect(moodle.callMoodleApi).not.toHaveBeenCalled();
    });

    it('propagates Moodle failures unchanged', async () => {
      moodle.callMoodleApi.mockRejectedValue(
        new Error('Moodle API exception: invalidcoursemodule'),
      );

      await expect(
        service.updatePrivatePage({
          courseId: 12,
          moodleUserId: 42,
          cmId: 601,
          contentHtml: '<p>Updated</p>',
        }),
      ).rejects.toThrow('Moodle API exception: invalidcoursemodule');
    });
  });
});
